name: Deploy Next.js App

on:
  push:
    branches:
      - main  # Change this if you're using a different deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      PORT: ${{ secrets.PORT }}
      NEXT_PUBLIC_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_PROJECT_ID }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build Next.js App
        run: pnpm build

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: PORT,NEXT_PUBLIC_PROJECT_ID
          script: |
            cd /root/Projects/Chromamind/web-app  # Change to your project's directory
            git checkout main
            git pull origin main  # Pull latest changes
            pnpm install # Install dependencies
            pnpm build  # Build the Next.js app
            pm2 restart web-app || PORT=$PORT pm2 start pnpm --name "web-app" -- start
